#!/bin/bash

if [[ -f "$HOME/.bashrc" ]]; then
    source $HOME/.bashrc
fi

mkdir -p ~/.icons
ln -sfT /usr/share/icons/Tango ~/.icons/hicolor
export XDG_RUNTIME_DIR=/tmp/runtime-$(whoami)
mkdir -p $XDG_RUNTIME_DIR
chmod 700 $XDG_RUNTIME_DIR

source /opt/ros/foxy/setup.bash
source /opt/intel/openvino/bin/setupvars.sh

if [[ -f "./install/local_setup.bash" ]]; then
    source ./install/local_setup.bash
fi

